def assert_fight(self, fight, expected):
    self.assertEqual(fight["event"], expected["event"])
    self.assertEqual(fight["fight_id"], expected["fight_id"])
    self.assertEqual(fight["link"], expected["link"])
    self.assertEqual(fight["fighter_one_id"], expected["fighter_one_id"])
    self.assertEqual(fight["fighter_two_id"], expected["fighter_two_id"])
    self.assertEqual(fight["weight_class"], expected["weight_class"])
    self.assertEqual(fight["method"], expected["method"])
    self.assertEqual(fight["round"], expected["round"])
    self.assertEqual(fight["time"], expected["time"])
    self.assertEqual(fight["belt"], expected["belt"])
    self.assertEqual(fight["bonus"], expected["bonus"])
    self.assertEqual(fight["wl_fighter_one"], expected["wl_fighter_one"])
    self.assertEqual(fight["wl_fighter_two"], expected["wl_fighter_two"])
