version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data: