version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5435:5432
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always

volumes:
  postgres_data:
