version: "3.8"

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

  django:
    build: .
    command: gunicorn ufcapi.wsgi:application -c /usr/src/app/gunicorn.conf.py
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env

  celery:
    build: .
    entrypoint: /usr/src/app/celery-entrypoint.sh
    command: celery -A ufcapi worker -B -l INFO
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 8000:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
