# Generated by Django 4.2.6 on 2023-11-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufcscraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="round",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fight",
            name="time",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
