# Generated by Django 4.2.6 on 2023-11-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufcscraper", "0003_alter_fight_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fighter",
            name="height",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
