# Generated by Django 4.2.6 on 2023-11-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufcscraper", "0004_alter_fighter_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="weight_class",
            field=models.CharField(
                choices=[
                    ("Heavyweight", "Heavyweight"),
                    ("Light Heavyweight", "Light Heavyweight"),
                    ("Middleweight", "Middleweight"),
                    ("Welterweight", "Welterweight"),
                    ("Lightweight", "Lightweight"),
                    ("Featherweight", "Featherweight"),
                    ("Bantamweight", "Bantamweight"),
                    ("Flyweight", "Flyweight"),
                    ("Women's Featherweight", "Women's Featherweight"),
                    ("Women's Bantamweight", "Women's Bantamweight"),
                    ("Women's Flyweight", "Women's Flyweight"),
                    ("Women's Strawweight", "Women's Strawweight"),
                    ("Catch Weight", "Catch Weight"),
                ],
                max_length=50,
            ),
        ),
    ]
