# Generated by Django 4.2.6 on 2023-11-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufcscraper", "0005_alter_fight_weight_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="fight",
            name="position",
            field=models.IntegerField(null=True),
        ),
    ]
