# Generated by Django 4.2.6 on 2023-11-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ufcscraper", "0007_alter_fight_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="fight",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="ufcscraper.fighter",
            ),
        ),
    ]
