# Generated by Django 4.2.6 on 2023-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufcscraper", "0010_alter_fight_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fight",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("U-DEC", "Unanimous Decision"),
                    ("S-DEC", "Split Decision"),
                    ("M-DEC", "Majority Decision"),
                    ("KO/TKO", "KO/TKO"),
                    ("SUB", "Submission"),
                    ("CNC", "Could Not Continue"),
                    ("Overturned", "Overturned"),
                    ("DQ", "Disqualification"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
