# Generated by Django 4.2.6 on 2023-12-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ufcscraper", "0011_alter_fight_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tricode", models.CharField(max_length=3, unique=True)),
                ("flag_url", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="fighter",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ufcscraper.country",
            ),
        ),
    ]
