# Generated by Django 4.2.6 on 2023-11-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redegg", "0007_alter_prognostic_bonus"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW redegg_global_leaderboard AS
            SELECT EXTRACT(YEAR FROM event.date) AS year, prediction.user_id, SUM(prediction.score) AS total_score
            FROM redegg_prediction AS prediction
            JOIN redegg_contest AS contest ON prediction.contest_id = contest.id
            JOIN ufcscraper_event AS event ON contest.event_id = event.id
            GROUP BY year, prediction.user_id
            ORDER BY year DESC, total_score DESC;
            """,
            "DROP MATERIALIZED VIEW redegg_global_leaderboard",
        ),
        migrations.CreateModel(
            name="GlobalLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.IntegerField()),
            ],
            options={
                "db_table": "redegg_global_leaderboard",
                "managed": False,
            },
        ),
    ]
