# Generated by Django 4.2.6 on 2023-12-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ufcscraper", "0011_alter_fight_method"),
        ("redegg", "0009_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="ufcscraper.event"
            ),
        ),
    ]
