# Generated by Django 4.2.6 on 2023-12-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redegg", "0010_alter_contest_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="base_username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
