# Generated by Django 4.2.6 on 2023-12-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("redegg", "0012_prediction_rank"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP MATERIALIZED VIEW redegg_global_leaderboard",
            """
            CREATE MATERIALIZED VIEW redegg_global_leaderboard AS
            SELECT EXTRACT(YEAR FROM event.date) AS year, prediction.user_id, SUM(prediction.score) AS total_score
            FROM redegg_prediction AS prediction
            JOIN redegg_contest AS contest ON prediction.contest_id = contest.id
            JOIN ufcscraper_event AS event ON contest.event_id = event.id
            GROUP BY year, prediction.user_id
            ORDER BY year DESC, total_score DESC;
            """,
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW redegg_global_leaderboard AS
                SELECT 
                    EXTRACT(YEAR FROM event.date) AS year, 
                    prediction.user_id, 
                    SUM(prediction.score) AS total_score,
                    ROW_NUMBER() OVER (PARTITION BY EXTRACT(YEAR FROM event.date) ORDER BY SUM(prediction.score) DESC) as rank
                FROM 
                    redegg_prediction AS prediction
                    JOIN redegg_contest AS contest ON prediction.contest_id = contest.id
                    JOIN ufcscraper_event AS event ON contest.event_id = event.id
                GROUP BY 
                    year, 
                    prediction.user_id
                ORDER BY 
                    year DESC, 
                    total_score DESC;
            """,
            "DROP MATERIALIZED VIEW redegg_global_leaderboard",
        ),
        migrations.AddField(
            model_name="globalleaderboard",
            name="rank",
            field=models.IntegerField(),
        ),
        migrations.AlterModelOptions(
            name="globalleaderboard",
            options={
                "db_table": "redegg_global_leaderboard",
                "managed": False,
            },
        ),
    ]
